[package]
name = "lisp_rs"
description = "Rust Implementation of an Lisp-like Language"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12"
